[workspace]

members = [
  "tuples",
  "colors",
  "canvas",
  "matrices",
  "transformations",
  "rays",
  "lights",
  "materials",
  "world",
  "camera",
  "cannon",
  "clock",
  "draw_sphere",
  "draw_scene"
]