[workspace]

members = [
  "tuples",
  "colors",
  "canvas",
  "matrices",
  "transformations",
  "rays",
  "spheres",
  "intersections",
  "lights",
  "materials",
  "cannon",
  "clock",
  "draw_sphere"
]