[package]
name = "materials"
version = "0.1.0"
authors = ["beagleknight <david.morcillo@gmail.com>"]
edition = "2018"

[dependencies]
colors = { path = "../colors" }
tuples = { path = "../tuples" }
lights = { path = "../lights" }